[package]
name = "Apex"
version = "0.1.0"
edition = "2021"

[dependencies]
maths_toolbox = { version = "0.1.0", path = "libs/maths_toolbox" }
simulation_toolbox = { version = "0.1.0", path = "libs/simulation_toolbox" }
